apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "acg-front-end.fullname" . }}-proxy-config
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |
    server {
        listen       80;
        server_name  _;
        
        location / {
            proxy_pass http://front-end-service/;
        }
        location /resources-api/ {
            proxy_pass http://resources-api-service/;
        }
        location /inventory-api/ {
            proxy_pass http://inventory-api-service/;
        }
        location /renting-api/ {
            proxy_pass http://renting-api-service/;
        }
        location /clients-api/ {
            if ($request_method = 'POST') {

                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Credentials' 'true';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
                add_header 'Access-Control-Allow-Headers' 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

            }
            proxy_pass http://clients-api-service/;
        }
        
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }