name: frontend-docker
run-name: It is a Dockerization workflow for Frontend EKS/ECS Project ðŸš€
on:
  push:
    branches:
    - 'master'
    - 'feature/**'
    paths:
    - 'front-end/**'
  pull_request:
    branches:    
    - master
    paths:
    - 'front-end/**'
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
env:
  AWS_REGION: us-east-1
  REPOSITORY_NAME: front-end
jobs:
  env-tag:
    name: Get Docker Image Tag
    runs-on: ubuntu-latest  
    outputs:
      imageTag: ${{ steps.env-tag.outputs.tag }}
    steps:
    - uses: actions/checkout@v4
    - name: Set env Tag
      id: env-tag
      run: |
        TAG=`git log -1 --pretty=format:%H | cut -c -9`
        echo "tag=$TAG"  >> $GITHUB_OUTPUT
  build-only:
    if:  startsWith(github.ref , 'refs/heads/feature/')
    needs:
    - env-tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: arn:aws:iam::464498973176:role/github-action-sysadmin
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_REGION }}
    - name: Login ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Build Only
      uses: docker/build-push-action@v5
      with:
        context: ./front-end
        file: ./front-end/Dockerfile
        push: false
        tags: ${{ steps.login-ecr.outputs.registry }}/${{env.REPOSITORY_NAME}}:${{ needs.env-tag.outputs.imageTag }}
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ steps.login-ecr.outputs.registry }}/${{env.REPOSITORY_NAME}}:${{ needs.env-tag.outputs.imageTag }}
        format: 'sarif'
       # exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
   #     output: 'trivy-results.sarif'
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  build-and-push:
    if: github.event_name == 'push' &&  github.ref =='refs/heads/master'
    needs:
        - env-tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: arn:aws:iam::464498973176:role/github-action-sysadmin
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_REGION }}
    - name: Login ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./front-end
        file: ./front-end/Dockerfile
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/${{env.REPOSITORY_NAME}}:${{ needs.env-tag.outputs.imageTag }}